# Default values for rucio.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# When set, run extra busybox containers in the relevant pods to also expose the error logs
exposeErrorLogs: True

# replicaCount gives the number of server pods to run
replicaCount: 1

strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 1

minReadySeconds: 5

image:
  repository: maany/rucio-webui
  tag: release-1.29.0-pre-alpha
  pullPolicy: Always

service:
  type: NodePort
  # Run the webui server on port 443 instead of 80 and accept X509 certificates
  useSSL: true
  nodePort: 30734
  annotations:
    # loadbalancer.openstack.org/proxy-protocol: 'true'
    # loadbalancer.openstack.org/cascade-delete: 'false'
    # loadbalancer.openstack.org/network-id: 798d00f3-2af9-48a0-a7c3-a26d909a2d64
    # service.beta.kubernetes.io/openstack-internal-load-balancer: 'true'
    

ingress:
  enabled: false
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  path: /
  hosts: []
  #   - my.rucio.test

additionalSecrets: []
# - volumeName: gcssecret
#   secretName: gcssecret
#   mountPath: /opt/rucio/etc/gcs_rucio.json
#   subPath: gcs_rucio.json

config:
  ## values used to configure apache, sets environment variables in the webui container that begin with RUCIO_HTTPD_
  httpd:
    legacy_dn: "False"
    # mpm_mode: "event"
    # start_servers: "1"
    # min_spare_threads: "1"
    # max_spare_threads: "20"
    # threads_per_child: "5"
    # max_clients: "20"
    # max_requests_per_child: "8192"
    # timeout: 300
    # min_spare_servers: "1"
    # max_spare_servers: "5"
    # server_limit: "10"
    # keep_alive: "On"
    # keep_alive_timeout: "5"
    # max_keep_alive_requests: "128"
    # threads_limit: "128"
    # max_request_workers: "1280"
    # max_connections_per_child: "2048"

  ## Rucio WebUI specific configuration for apache 
  httpdWebui:
    hostname: atlas-rucio-webui.cern.ch
    # server_admin:
    logLevel: 'info'

  ## Configuration for OIDC providers
  # oidcProviders: #[]
  #   - name: "CERN SSO"
  #     client_id: "rucio-webui"
  #     authorization_endpoint: "https://login.cern.ch/adfs/oauth2/authorize"
  #     token_endpoint: "https://login.cern.ch/adfs/oauth2/token"
  #     redirect_uri: "https://rucio-webui.cern.ch/auth/oidc/callback"
  #     scopes: "openid profile email"

  ## Configuration for the WebUI React App
  react:
    rucioHost: https://rucio-devmaany.cern.ch
    rucioAuthHost: https://rucio-devmaany.cern.ch
    # webui_login_page_image_primary: "" Mount the image as secret and set the path here
    # webui_login_page_image_secondary: "" Mount the image as secret and set the path here


# additional environment variables to set in the webui container
optionalConfig: {}


resources: {}
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
