{{- if gt .Values.replicaCount 0.0 -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "rucio.fullname" . }}
  labels:
    app: {{ template "rucio.name" . }}
    chart: {{ template "rucio.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- with .Values.service.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  type: {{ $.Values.service.type }}
  ports:
    - port: {{ ternary 443 80 $.Values.service.useSSL }}
      targetPort: {{ ternary "https" "http" $.Values.service.useSSL }}
      protocol: TCP
      {{- if $.Values.service.nodePort }}
      nodePort: {{ $.Values.service.nodePort }}
      {{- end }}
      name: {{ ternary "https" "http" $.Values.service.useSSL }}
  selector:
    app: {{ template "rucio.name" . }}
    release: {{ .Release.Name }}
{{- end }}